### ISSUE TITLE
EVA on BLV

### ISSUE THREAD

**Issue by pkucmus** [EVA-3D/eva-main#8]
Moved from EVA 1: https://github.com/pkucmus/EVA/issues/32

**Comment by pkucmus** [comment]
This maybe a more of a BLV project than EVA project but for the sake of tracking I'll leave this here

**Comment by morpheus200** [comment]
After your upgrade to EVA 2 and support of the Mosquito Hotend (Thanks a lot) i have printed all parts and have also encountered this problem. Mirroring the front helps but for the rear side this is not possible because the fan is the wrong way round.
It looks like it is a problem with the BLV Cube design, because the belts are guided differently.

**Comment by damik422** [comment]
Hey I have a hevort not a BLV but the belt path is similar. I have a problem, the rear belts are flipped so that the teeth side faces away from the 2020 extrusion. The belt holders are designed for the belts facing the other way around. Is there a way to mitigate that or do i have to modify the belt holders so that they have teeth on the other side of the channel for the belt? ps. im using 6mm belts

**Comment by pkucmus** [comment]
> Hey I have a hevort not a BLV but the belt path is similar. I have a problem, the rear belts are flipped so that the teeth side faces away from the 2020 extrusion. The belt holders are designed for the belts facing the other way around. Is there a way to mitigate that or do i have to modify the belt holders so that they have teeth on the other side of the channel for the belt? ps. im using 6mm belts

Please check in the Onshape document in the 'backs' folder. There's a high chance those are already there.

**Comment by pkucmus** [comment]
Here: https://cad.onshape.com/documents/1765b04fac582f6c1c470bd3/w/1cc31596374d6ce51cd23fa9/e/626c5e88e2db7d8a29b52142
![flip](https://user-images.githubusercontent.com/6347418/110449797-daee6780-80c2-11eb-9ef6-3d06e84c93b7.gif)

**Comment by tetele** [comment]
Finally published the conversion kit for the BLV MGN Cube on the contributions repo https://contrib.eva-3d.page/printer-compatibility/blv-mgn-cube/
