### ISSUE TITLE
Bl-touch mount 

### ISSUE THREAD

**Issue by duniu9** [EVA-3D/eva-main#83]
The Bl-touch mount is too thick and collides with the sensor. There is 8mm space for the bl-touch, the mount is 9.5mm thick.
![Bl-touch](https://user-images.githubusercontent.com/105736593/168854485-fbc7bc9d-2dd5-4335-bc09-326b9110a2b7.jpg)

**Comment by duniu9** [comment]
Another problem is the sensor collision with the shroud
![bl](https://user-images.githubusercontent.com/105736593/168868307-0e10c1e3-4dd7-48d4-8f19-bd3d57eda68e.jpg)

**Comment by mikejwaters** [comment]
I also had the same problem. I shaved away the excess after printing to put the BLtouch on it's mount.

**Comment by pkucmus** [comment]
The shroud compatibility is something I'll think about more, will likely produce many different shrouds.
As for the mount, please test this: https://cad.onshape.com/documents/cb8bd513b980b411d50cd513/w/6f7fd7828c4d7cb1c0c853da/e/dbf188e21e46a24ca801cc78

**Comment by mpx1986** [comment]
the next Problem ist the fan shroud

**Comment by mbiedak** [comment]
New version is correct in height, but I am unable to fit it with cables attached. You can see that on the picture above

**Comment by mbiedak** [comment]
@duniu9 can you share with me your updated file?

**Comment by duniu9** [comment]
> @duniu9 can you share with me your updated file?

[Bl-touch fix.zip](https://github.com/EVA-3D/eva-main/files/8777071/Bl-touch.fix.zip)

**Comment by pkucmus** [comment]
BL-Touch is tricky as it has many versions and revisions, some say it works for some it does not, can you post real life pictures here for me to better understand what is going on?

**Comment by sladewexo** [comment]
Though the bl-touch fitted for me, it was sitting to low on my V-Core 3 500.  I altered @pkucmus design a bit to move it higher up.  For those interested, I've included the STL and STEP file here
[bltouch.zip](https://github.com/EVA-3D/eva-main/files/8796484/bltouch.zip)
.

**Comment by mikejwaters** [comment]
> BL-Touch is tricky as it has many versions and revisions, some say it works for some it does not, can you post real life pictures here for me to better understand what is going on?

@pkucmus I know it's inelegant, but would having a printable shim help with BL-Touch compatibility? Just a thought.

**Comment by pkucmus** [comment]
I made a bunch of improvements to the BL-Touch mount, please tell me how it works, EVA 3.0 was just released: https://main.eva-3d.page/heat_insert/probes/bl_touch/

**Comment by b33k-WA** [comment]
I really struggled to get the nuts into the recesses, perhaps a little more tollerance, I ended up having to print the piece 3x because of bending the thin arm when trying to pull the nut into place and another when it spun.  I ended up printing at a high infill and setting the nut like a brass insert (sorry I know you hate those).  Once I got it on the machine I encountered issues with not having any adjustment available and felt it was too close to run. 

![IMG_1335](https://user-images.githubusercontent.com/95461285/173274267-f23bf897-d5b0-48ac-b833-0e920c385239.jpeg)
![IMG_1334](https://user-images.githubusercontent.com
![IMG_1333](https://user-images.githubusercontent.com/95461285/173274417-ca98a25f-cfd5-4b97-b846-706c640bf7b4.jpeg)
/95461285/173274287-9dac702b-dccb-49d5-bbc8-492a2a12534c.jpeg)
